Projects/CoX/CMakeLists.txt, Projects/CoX/Servers/MapServer/MapInstance.cpp
Removes the duplicate copy of the new README from the default_dbs folder
=> Remove duplicate README.md and fix typo for Broadcast Chat

Projects/CoX/Servers/AdminServer/CharacterDatabase.cpp, Projects/CoX/Servers/MapServer/Events/ChatMessage.cpp, Projects/CoX/Servers/MapServer/MapInstance.cpp
Removed superfluous space from check for chat commands. Fixes error with `/b` not working
Addresses #66
=> Fixed issue with broadcast channel not working

Projects/CoX/Servers/MapServer/MapInstance.cpp
First run at #155
- add handler for /smilex {filename} command
- load contents of {filename} into dlg
- error msg if none found
ToDo:
- Parse smlx file?? Not sure the end goal with /smilex, is it just for testing only?
=> Added Smilex slash command which loads smlx folder from ./scripts/

Projects/CoX/Common/GameData/def_serializers.cpp, Projects/CoX/Common/GameData/def_serializers.h, Projects/CoX/Servers/MapServer/MapServerData.cpp, Projects/CoX/Servers/MapServer/MapServerData.h, Projects/CoX/Utilities/BinConverter/binConverter.cpp
Closes #176 .
- experience.bin is handled by binConverter
- experience and debt data is available from MapServerData
=> Add experience per level and debt to MapServerData

Projects/CoX/Servers/AuthServer/main.cpp
This is meant as a step towards making more segs elements thread independent
( using qt queued signal slots to simulate ace messages and queues )
=> Add qt message loop processing.

Components/CMakeLists.txt, Components/Settings.cpp, Components/Settings.h, Projects/CoX/Common/Servers/AdminServerInterface.cpp, Projects/CoX/Common/Servers/AdminServerInterface.h, Projects/CoX/Common/Servers/AuthServerInterface.cpp, Projects/CoX/Common/Servers/AuthServerInterface.h, Projects/CoX/Common/Servers/GameServerInterface.cpp, Projects/CoX/Common/Servers/GameServerInterface.h, Projects/CoX/Common/Servers/MapServerInterface.cpp, Projects/CoX/Common/Servers/MapServerInterface.h, Projects/CoX/Common/Servers/RoamingServer.cpp, Projects/CoX/Common/Servers/RoamingServer.h, Projects/CoX/Common/Servers/Server.h, Projects/CoX/Common/Servers/ServerManager.cpp, Projects/CoX/Common/Servers/ServerManager.h, Projects/CoX/Data/settings.cfg, Projects/CoX/Servers/AdminServer/AdminServer.cpp, Projects/CoX/Servers/AdminServer/AdminServer.h, Projects/CoX/Servers/AuthServer/AuthServer.cpp, Projects/CoX/Servers/AuthServer/AuthServer.h, Projects/CoX/Servers/AuthServer/main.cpp, Projects/CoX/Servers/GameServer/GameServer.cpp, Projects/CoX/Servers/GameServer/GameServer.h, Projects/CoX/Servers/MapServer/MapInstance.cpp, Projects/CoX/Servers/MapServer/MapServer.cpp, Projects/CoX/Servers/MapServer/MapServer.h
Closes #89
- New `Settings` class
- New `getSettings()` static function
- New `setSettingsPath()` static function
- New `getSettingsPath()` static function
- New `settingsDump()` function
- New `/settingsdump` slash command
- Changed `m_account_slots` to `m_character_slots` for clarity
- Added several missing `QSettings::endgroup()` methods and commented for clarity
- Added some debug messages
- Recoded AdminServer, AuthServer, GameServer, MapServer, and RoamingServer to use new Settings class.
- Tested several times trying to bork the system. Seems OK :+1: 
TODO: As far as I can tell nothing :+1: 
NOTE: `setDefaultSettings()` will delete ALL comments in the `settings.cfg` file. This is "expected" QSettings behavior. :frowning_face:
=> Qsettings wrapper Settings

Projects/CoX/Servers/MapServer/MapInstance.cpp, Projects/CoX/Servers/MapServer/SlashCommand.cpp, Projects/CoX/Servers/MapServer/SlashCommand.h
Resolves lingering slashcommand created by PR #264 and #265 merging around the same time.
Closes #269.
- Moved `/settingsdump` to SlashCommands.cpp
=> Fix for qsettings branch slashcommand merge

Projects/CoX/Common/Servers/RoamingServer.cpp, Projects/CoX/Servers/AdminServer/AdminServer.cpp, Projects/CoX/Servers/AuthServer/AuthServer.cpp, Projects/CoX/Servers/GameServer/GameServer.cpp, Projects/CoX/Servers/MapServer/MapServer.cpp
Hi all, 
First contribution! @Jhon in Discord... 
Changed the qWarning() calls at the relevant places into qInfo() calls to not alarm the end-user. 
Closes #274 (hopefully)
=> Issue #274 - Settings load messages categorized as warnings

Projects/CoX/Servers/MapServer/SlashCommand.cpp
Addresses #282 
* Changed uses of split for commands with single args to midRef(indexOf(" ")+1)
* Used a splitRef for SetSpeed without the conversion checking
* Changed the Info output of setSpeed to indicate it is setting a vector via use of "< , , >".
Tested a few commands like /setHP and /setSpeed in-game with no errors, though visually wasn't sure what setSpeed was actually doing to verify with the rubber-banding issue currently present.
=> Address Issue #282 in the SlashCommand handlers

Projects/CoX/Servers/MapServer/MapServerData.cpp
Closes #292  .
- Change qWarnings to qInfo within Projects/CoX/Servers/MapServer/MapServerData.cpp
- Cleans up server output
=> Update qWarnings to qInfo within Projects/CoX/Servers/MapServer/MapServerData.cpp

Projects/CoX/Common/GameData/chardata_definitions.h, Projects/CoX/Common/GameData/chardata_serializers.cpp, Projects/CoX/Common/GameData/entitydata_definitions.h, Projects/CoX/Common/GameData/entitydata_serializers.cpp
Closes #298.
My C++ is a little bit rusty but this should fit the bill. These are the only 2 versioned serialization functions I could find.
- Display an error if the serialization version argument does not match the version of the object to be serialized
- Add macro / constant for current object version
=> Error out when passing the wrong version into versioned serializers

Projects/CoX/Utilities/dbtool/main.cpp
This adds a command argument to the dbtool utility
* `create`  creates the database, same as the dbtool did before
* `adduser -l login -p password`   adds a new account to the database
=> Since auto-account creation is going away, the db tool needs to step in

Projects/CoX/Common/NetStructures/Team.cpp
Probably closes #309 , and even if it doesn't it's a good idea to look for nullptrs before touching them.
=> Added nullptr check to leaveTeam()

Projects/CoX/Common/GameData/gui_definitions.h, Projects/CoX/Common/NetStructures/Character.cpp, Projects/CoX/Common/NetStructures/Entity.cpp, Projects/CoX/Servers/MapServer/MapClient.cpp
- Fix m_access_level by pulling value from `accountInfo()`.
- Initialize window settings to 0 (hopefully this fixes random crashing when server is running debug mode)
=> Couple small fixes to m_account_level and Windows serialization

Projects/CoX/Servers/MapServer/CMakeLists.txt, Projects/CoX/Servers/MapServer/DataHelpers.cpp, Projects/CoX/Servers/MapServer/DataHelpers.h, Projects/CoX/Servers/MapServer/Events/EmailHeaders.h, Projects/CoX/Servers/MapServer/Events/EmailMessageStatus.h, Projects/CoX/Servers/MapServer/Events/EmailRead.h, Projects/CoX/Servers/MapServer/Events/MapEventTypes.h, Projects/CoX/Servers/MapServer/SlashCommand.cpp, Projects/CoX/Servers/MapServer/SlashCommand.h
**Additions:**
* Adds the EmailHeaders and EmailRead game commands
* Adds the EmailHeaders, EmailMessageStatus, and EmailRead events
* Support the sending of multiple headers or a single email header
Current functionality is just sending a test email header and email read with the same ID.
**TODO:**
* Add emails to the database with EmailSend (This will likely require some input sanitizing)
Ex. /emailsend "\q[Name]\q " "Subject" "Content"
* Send EmailMessageStatus event on Success/Failure of Send, rather than using a InfoMessageCmd
* Add timestamp generation as the client does not send this information - This is the number of seconds elapsed since Y2K relative to the server's defined timezone (Currently 0, -12 GMT).
* Remove emails from database with EmailDelete (Will need to check that …
=> [RFC] Email System

Projects/CoX/Servers/AuthServer/AuthHandler.cpp, Projects/CoX/Servers/AuthServer/AuthHandler.h
Affected files:
AuthHandler.cpp and AuthHandler.h
- Zero-Terminate the login and password arrays of ev casted as a LoginRequest
Suggestions to save more coding space:
- Maybe make it so that we don't have to call the function before every return (Call the function inside the switch case instead?)
=> Fixing Issue #227 (Zero-Termination of Login and Password Arrays)

Projects/CoX/Servers/MapServer/CMakeLists.txt, Projects/CoX/Servers/MapServer/Events/InteractWithEntity.h, Projects/CoX/Servers/MapServer/Events/MapEventTypes.h, Projects/CoX/Servers/MapServer/MapEventFactory.cpp, Projects/CoX/Servers/MapServer/MapEvents.h, Projects/CoX/Servers/MapServer/MapInstance.cpp, Projects/CoX/Servers/MapServer/MapInstance.h
Server should no longer crash when clicking on spawned npcs
=> Add support for `Interact with this` packets

Projects/CoX/Data/mysql/segs_game_mysql_create.sql, Projects/CoX/Data/mysql/segs_mysql_create.sql, Projects/CoX/Utilities/dbtool/CMakeLists.txt, Projects/CoX/Utilities/dbtool/main.cpp
- dbtool now cares about settings.cfg
- dbtool always selects db_driver and db_name from settings.cfg
- If db_driver != QSQLITE, db_host, db_port, db_user and db_pass from settings.cfg is used
- Both database creation and user addition works
Left to do:
- ~~dbtool will not work if selected MySQL database is not available~~
- ~~dbtool will not work if a MySQL table already exists~~
- ~~dbtool does not check if MySQL database is available before trying to execute queries~~
- ~~dbtool does not fetch settings file name dynamically (i.e. "settings.cfg" is hard coded)~~
Updated: If user has permissions, new databases will be created.
If -force is provided, old tables will be dropped and new ones created.
-c/--config switch used to select …
=> Added MySQL and PostgreSQL support in dbtool.

Projects/CoX/Utilities/SEGSAdmin/SEGSAdminTool.cpp
Closes #391  .
Restructured QProcess program/arguments to remove specific pointer to 'cmd.exe.' / 'xterm' etc, fixes issue on Fedora where xterm not installed by default
=> SEGSAdmin tool - fix for Fedora (and possibly other Linux distros)

Projects/CoX/Clients/Client_I0_Null/CMakeLists.txt, Projects/CoX/Clients/Client_I0_Null/dll_core.cpp, Projects/CoX/Clients/Client_I0_Null/patch_all_the_things.cpp, Projects/CoX/Clients/Client_I0_Null/patch_all_the_things.h, Projects/CoX/Utilities/MapViewer/src/CohModelConverter.cpp
This is useful when trying to debug the patched client crashes ( patched client has many named functions exported, so stack traces in debuggers that can use them, are much more readable )
=> Add 'null' client patch.

Projects/CoX/Utilities/SEGSAdmin/AddNewUserDialog.cpp
Access level ui controls are hidden on 'create admin user' as it's set to level 9. However, if the user then tried to add a user through the normal 'Add User' flow, the access level ui control wasn't being shown. This is now fixed.
Bug fix for #285
=> SEGSAdmin - Bug fix on 'Add User', not asking for access level

Projects/CoX/Data/mysql/segs_game_mysql_create.sql, Projects/CoX/Data/mysql/segs_mysql_create.sql, Projects/CoX/Data/pgsql/segs_game_postgres_create.sql, Projects/CoX/Data/sqlite/segs_game_sqlite_create.sql, Projects/CoX/Servers/GameDatabase/GameDBSyncContext.cpp, Projects/CoX/Servers/GameDatabase/GameDBSyncContext.h
Characters are created/stored with 'account_id' value of
chardb->accounts->account_id, whereas they are/were looked up with the
chardb->accounts->id value. Those two values are not necessarily the same.
Update: So, a lot of stuff happened.
- Progress table was removed as it fits in nicely inside the characters table as a blob.
- #393 was taken care of as the scripts are already modified anyways.
- MySQL creation scripts were fixed, as they would complain/error out if the database was already populated due to foreign key constraints.
- CharDB->accounts table lost its 'id' entry as it's not used. account_id from the same table has since been renamed 'id'.
- Supergroups now only have one id column.
=> Fixed "character select list" query.

Projects/CoX/Utilities/dbtool/main.cpp
Issue #408
I removed the automatic creation of admin when creating new databases or forcing the creation of new databases. In it's place, use qInfo to insert 3 lines of text. The first line warns the user that no admin account was created. The next line lets the user know that to create an admin, follow the schema on the next line. The final line is the schema to follow to add a user. I have included two brief comments above this small block listing what was changed.
Closes # .
- 
- 
-
=> Removed automatic admin from dbtool and included text about adduser

Projects/CoX/Common/NetStructures/Entity.cpp, Projects/CoX/Servers/MapServer/DataHelpers.cpp, Projects/CoX/Servers/MapServer/DataHelpers.h, Projects/CoX/Servers/MapServer/EntityUpdateCodec.cpp, Projects/CoX/Servers/MapServer/Events/InputState.cpp, Projects/CoX/Servers/MapServer/Events/InputState.h, Projects/CoX/Servers/MapServer/Events/MapEventTypes.h, Projects/CoX/Servers/MapServer/MapInstance.cpp, Projects/CoX/Servers/MapServer/SlashCommand.cpp
Fixed green reticle issue and corrected Target Assist IDX
Closes #392 
- Fixed issues with sending Targets to the Client (fixing #392)
- Set `m_assist_target_idx` server side since the client never sends us this information
Outstanding:
- TODO: Outstanding issue with `/assist` because target is overwritten by client to old value
=> Fixed green reticle issue and corrected Target Assist

Projects/CoX/Common/AuthProtocol/AuthLink.cpp, Projects/CoX/Common/NetStructures/StateInterpolator.cpp, Projects/CoX/Common/NetStructures/Team.cpp, Projects/CoX/Common/Runtime/SceneGraph.cpp, Projects/CoX/Common/Servers/ClientManager.h, Projects/CoX/Servers/AuthServer/AuthHandler.cpp, Projects/CoX/Servers/MapServer/EntityUpdateCodec.cpp, Projects/CoX/Servers/MapServer/Events/EntitiesResponse.cpp, Projects/CoX/Servers/MapServer/MapInstance.cpp, Projects/CoX/Servers/MapServer/NetCommandManager.cpp, Projects/CoX/Servers/MapServer/ScriptingEngine_Null.cpp, Utilities/slav/SLAVLogic.cpp, Utilities/slav/ServerConnection.cpp
This pull request addresses any remaining compiler warnings outlined in #352 with the exception of those stemming from Qt GUI-related casts pertaining to callback functions. As a result, SEGSAdmin and SLAV will remain affected until the Qt developers address the reported casting issues up to 5.9. `Q_UNUSED` is employed as self-documenting way to quell unused var warnings. It is easily searchable and can be used to locate and address each finding in the future. Various casts and format specifiers were also fixed which should help with truncation in certain cases.
=> Compiler warning fixes to address #352

Projects/CoX/Utilities/AuthExerciser/CMakeLists.txt
Fixes cmake parse error
Closes #429  .
=> add PUBLIC to target_link_libraries in AuthExerciser

Projects/CoX/Servers/MapServer/MapInstance.cpp, Projects/CoX/Servers/MapServer/MapManager.cpp, Projects/CoX/Servers/MapServer/MapServer.cpp, Projects/CoX/Servers/MapServer/MapServer.h
- Add more detailed startup message in MapServer and some refactoring to use constants. Removed an member field.
- Fix a typo in MapInstance::spin_up_for() and add a startup message.
- Convert qCDebug() statements to qDebug() statements in MapManager to print them in the console.
=> Improve readability in several MapServer files

Projects/CoX/Servers/MapServer/SlashCommand.cpp
Closes nothing as I have not opened any issue for this.
If you want me to, then I will do so.
- Fixed a crash in "addNpc" slash command when executing it without any parameters. There was a missing "return" statement after a sanity check.
=> Fixed a crash in "addNpc" slash command when executing it without any parameters.

CMakeScripts/Windeployqt.cmake
This change makes it possible to run the executables in the "out" directory without using QtCreator.
Closes nothing as I have not opened any issue for this.
If you want me to create an issue first, then I will do so.
- When I tried to run any built executable in my Win8/MINGW development environment it failed with an error message telling me that it could not find the "libwinpthread-1.dll" library. Running from QtCreator works fine though. This change adds the missing library to the "out" directory, just as the other MINGW specific files are.
=> Added missing "libwinpthread-1.dll" library to MINGW build.

Projects/CoX/docs/README.md
It has become a somewhat regular issue that people fail to modify the `Target:` line in their CoX.exe shortcut. They get an error that the target is invalid when trying to add `-project SEGS`.  
9/10 times this is due to a missing space (" ").
- Clarify what the `Target:` line ought to look like.
=> Clarifying format for 'Target:'

CMakeLists.txt, Components/Settings.cpp, Projects/CoX/CMakeLists.txt, Projects/CoX/Data/settings_template.cfg, Projects/CoX/Utilities/SEGSAdmin/SettingsDialog.cpp
Now an empty directory structure which is required by the server is added by cmake.
The default setting in settings.cfg is changed, too.
~~Not ready for merge yet~~: 
default value changed: 
And while I was at it, I renamed the settings.cfg created by cmake to settings_template.cfg
=> Added DefaultMapInstances to the cmake structure.

Projects/CoX/Common/GameData/chardata_definitions.h, Projects/CoX/Common/GameData/chardata_serializers.cpp, Projects/CoX/Common/GameData/entitydata_definitions.h, Projects/CoX/Common/GameData/entitydata_serializers.cpp, Projects/CoX/Common/NetStructures/Character.cpp, Projects/CoX/Common/NetStructures/Character.h, Projects/CoX/Common/NetStructures/Entity.cpp, Projects/CoX/Common/NetStructures/Entity.h, Projects/CoX/Common/NetStructures/Friend.cpp, Projects/CoX/Servers/GameDatabase/GameDBSyncContext.cpp, Projects/CoX/Servers/GameDatabase/GameDBSyncEvents.h, Projects/CoX/Servers/GameServer/GameEvents.cpp, Projects/CoX/Servers/GameServer/GameHandler.cpp, Projects/CoX/Servers/GameServer/GameHandler.h, Projects/CoX/Servers/MapServer/DataHelpers.cpp, Projects/CoX/Servers/MapServer/DataHelpers.h, Projects/CoX/Servers/MapServer/MapInstance.cpp, Projects/CoX/Servers/MapServer/SlashCommand.cpp
I didn't expect to make so many changes... To summarize, this is about removing m_mapName from CharData and creating m_current_map in EntityData. I might be making too much changes at one go here.
This is compilable but untested, I will be awaiting your inputs before going in further.
- Updated serializers for CharData and EntityData
- Incremented class versions for affected structs
- Character::from/toActualCharacter now takes in EntityData as parameter, where it is going to be serialized to/from QString
- Character::reset and getCurrentCostume no longer deals with map names
- Created uniquePtr for EntityData in Entity
- GameAccountResponseCharacterData now has m_serialized_entity_data, which will be used by GameHandler
- GameHandler::on_map_req now gets the map name from …
=> Changing CharData::m_mapName to EntityData::m_current_map

include/version.h
This will (probably) prove itself useful for the Web UI.
VersionString is now split up into:
* ProjectName ("SEGS")
* VersionNumber ("0.5.0")
* VersionName ("(The Unsilencer)")
It is concatenated in VersionString which is returned by the same function as before.
A new function returning just the VersionNumber was added, as the strings themselves are undefined at the end of `version.h`.
=> Split up VersionString

Projects/CoX/Servers/MapServer/MapInstance.cpp
Closes #491 .
- Initialize MapInstance::m_index to the index value corresponding to map_name in `g_defined_map_datas`
Marked as WIP as I have not yet confirmed that the client agrees upon this map index usage.
=> [WIP] Initialize MapInstance::m_index correctly

Projects/CoX/Servers/GameDatabase/GameDBSyncContext.cpp, Projects/CoX/Servers/GameDatabase/GameDBSyncContext.h, Projects/CoX/Servers/GameDatabase/GameDBSyncEvents.h, Projects/CoX/Servers/GameDatabase/GameDBSyncHandler.cpp, Projects/CoX/Servers/GameDatabase/GameDBSyncHandler.h, Projects/CoX/Servers/MapServer/MapInstance.cpp, Projects/CoX/Servers/MapServer/MapInstance.h
It should work almost exactly like GetEntityRequest and GetEntityResponse, the only thing is using a character's name instead of db_id as the search criteria. I think my EmailHandler can use this, and perhaps other handlers that are made for player to player interactions can, as well. In the end, it is possible that we might not use this at all though :P
This is untested atm, and I have made nothing that would use these changes in this PR (so far). To test this, I will change up MapInstance's on_create_map_entity so that it queues GetEntityByNameRequest instead of the standard GetEntityRequest. I don't think I should commit this change to MapInstance, because the default way is already correct, and thus changing it is unnecessary.
=> Allowing DbHandler to get entity data using character name.

Projects/CoX/Servers/MapServer/MapInstance.cpp
Current develop HEAD is broken due to a merge miss.
- Remove the last reference to "setMapName()" in MapInstance.cpp
=> Remove `setMapName()` from MapInstance

appveyor.yml
Closes #530 
Due to issue #530 and after a discussion on discord, we're going to disable win32 build for now.
=> Updated appveyor disabling win 32 build

Projects/CoX/Common/GameData/trays_serializers.cpp, Projects/CoX/Common/NetStructures/Powers.h
=> Move power tray's serialization version macros to the header.

Components/Settings.cpp, Projects/CoX/Common/NetStructures/Character.cpp, Projects/CoX/Common/NetStructures/Character.h, Projects/CoX/Data/settings_template.cfg
Closes #572.
- moved starting powers and inspirations to settings.cfg
- added starting level and inf
=>  Starting character infromation read from settings.cfg 

Projects/CoX/Common/NetStructures/Entity.h, Projects/CoX/Servers/MapServer/CMakeLists.txt, Projects/CoX/Servers/MapServer/DataHelpers.cpp, Projects/CoX/Servers/MapServer/DataHelpers.h, Projects/CoX/Servers/MapServer/Events/AddTimeStateLog.h, Projects/CoX/Servers/MapServer/Events/GameCommandList.h, Projects/CoX/Servers/MapServer/Events/MapEventTypes.h, Projects/CoX/Servers/MapServer/Events/TimeUpdate.h, Projects/CoX/Servers/MapServer/SlashCommand.cpp, Projects/CoX/Servers/MapServer/UnitTests/MapEventRegistry.cpp
This PR pulls some of the features out of my Movement PR to simplify review and narrow the focus of #580 to movement related issues. I went ahead and added TimeUpdate as it may relate to syncing client with server when factoring latency
- Add AddTimeStateLog packet 60
- Add `/timestate` that takes an integer for control_log id
- Add TimeUpdate packet 48
- Add `/timeupdate` to test (no arguments)
Relates to two tasks in #519
=> AddTimeStateLog and TimeUpdate

Projects/CoX/Common/GameData/GameDataStore.cpp, Projects/CoX/Common/GameData/GameDataStore.h, Projects/CoX/Common/GameData/keybind_definitions.cpp, Projects/CoX/Common/NetStructures/Character.cpp, Projects/CoX/Common/NetStructures/Friend.cpp, Projects/CoX/Common/NetStructures/Friend.h, Projects/CoX/Common/NetStructures/Powers.cpp, Projects/CoX/Common/NetStructures/Powers.h, Projects/CoX/Common/NetStructures/Team.cpp, Projects/CoX/Common/NetStructures/Team.h, Projects/CoX/Servers/AuthServer/main.cpp, Projects/CoX/Servers/MapServer/DataHelpers.cpp, Projects/CoX/Servers/MapServer/DataHelpers.h, Projects/CoX/Servers/MapServer/EntityUpdateCodec.cpp, Projects/CoX/Servers/MapServer/Events/EntitiesResponse.cpp, Projects/CoX/Servers/MapServer/MapInstance.cpp, Projects/CoX/Servers/MapServer/MapInstance.h, Projects/CoX/Servers/MapServer/MapSceneGraph.cpp, Projects/CoX/Servers/MapServer/MapServer.cpp, Projects/CoX/Servers/MapServer/MapServer.h, Projects/CoX/Servers/MapServer/NpcGenerator.cpp, Projects/CoX/Servers/MapServer/SlashCommand.cpp
* GameData became a singleton
* Team and Friend support functions return their status as enums and the
caller is responsible for proper reporting.
This should fix some of the 'random' linking problems we sometimes encounter.
=> NetStructures no longer uses any of the MapServer internals:

Projects/CoX/Common/GameData/GameDataStore.cpp, Projects/CoX/Servers/MapServer/MapServer.cpp
Report multiple instantiations of GameDataStore.
=> Use a game data singleton in MapServer instead of it's own instance.

Projects/CoX/Common/GameData/GameDataStore.cpp, Projects/CoX/Common/GameData/chardata_serializers.cpp, Projects/CoX/Common/NetStructures/Character.cpp, Projects/CoX/Common/NetStructures/Character.h, Projects/CoX/Common/NetStructures/CharacterHelpers.cpp, Projects/CoX/Common/NetStructures/Powers.cpp, Projects/CoX/Servers/MapServer/SlashCommand.cpp
Closes #502.
Gets maxHP and maxEnd from AttribMaxTable, and sets based on class/archetype and level.
Also cleared up some more uses of combat_level, and changed it to be 0-49 for consistency with level.
The hp values are a little off from what the wiki lists, but these are the values in classes.bin.
At a latter date, AttribMaxTable could be overwritten from a cfg/lua file to customize the values.
=> get maxHP from classes.bin and cleaned up combat level

Projects/CoX/Common/NetStructures/Entity.h, Projects/CoX/Servers/MapServer/CMakeLists.txt, Projects/CoX/Servers/MapServer/DataHelpers.cpp, Projects/CoX/Servers/MapServer/DataHelpers.h, Projects/CoX/Servers/MapServer/Events/GameCommandList.h, Projects/CoX/Servers/MapServer/Events/MapEventTypes.h, Projects/CoX/Servers/MapServer/Events/Waypoints.h, Projects/CoX/Servers/MapServer/MapEvents.h, Projects/CoX/Servers/MapServer/MapInstance.cpp, Projects/CoX/Servers/MapServer/SlashCommand.cpp
Relates to #519 
- SendWaypoints event
- `/setwaypoint` to test. NOTE: client will only set waypoint if the idx is equal to the client-side idx. This creates a small issue where you cannot simply set a waypoint without one having been set already. In the future, we'll be able to do with with Tasks or Contacts. Right now, the only mechanism for doing so with in the UI (clicking on the map)
- Cleaned up a couple of small bugs in slashcommands
- Moved SetDestination to Waypoints.h for organization
=> Waypoints implementation with slash command to test `/setwaypoint`

Projects/CoX/Servers/MapServer/MapInstance.cpp, Projects/CoX/Servers/MapServer/ScriptingEngine.cpp
Added calls from C++ into lua for entity_interact and on_dialog_button
Lua script for entities would be entities.lua in the same folder as locations.lua and plaques.lua for the current zone
I couldn't get the QHash for contactLinkHash in Contact.h to work, so i'm sending the int from Lua instead of the string. Example (3 vs CONTACTLINK_BYE)
=> Exposed contact_dialog methods to Lua

appveyor.yml
Appveyor fails due to timeout. See if caching will fix that.
Also, iterate version number to v5, as we're cool like that
=> Testing cache theory on appveyor. Iterated version number

Components/Logging.cpp, Components/Logging.h, Components/Settings.cpp, Projects/CoX/Common/Runtime/SceneGraph.cpp, Projects/CoX/Data/settings_template.cfg
As title says, move the message ` debug: duplicate model trick!` into a log category.
Said logging category is a new one.
=> log: Put 'duplicate mod trick' in 'SceneGraph' category

Projects/CoX/Utilities/SEGSAdmin/SEGSAdminTool.cpp, Projects/CoX/Utilities/SEGSAdmin/SEGSAdminTool.h
Closes # none.
- fix SEGSAdmin failing to start "authserver", which was renamed to "segs_server"
- update UI, replacing "Auth Server" with "SEGS Server"
=> fix SEGSAdmin failing to start "authserver", which was renamed to "segs_server"

Projects/CoX/Servers/GameServer/GameServer.cpp
Closes #622.
- Close emailhandler on shutdown as it prevents the server from exiting otherwise
=> hotfix: Close emailhandler on shutdown

Projects/CoX/Common/CRUDP_Protocol/CRUDP_Protocol.cpp, Projects/CoX/Common/CRUDP_Protocol/CRUD_Link.cpp, Projects/CoX/Common/GameData/Entity.cpp, Projects/CoX/Servers/MapServer/MapInstance.cpp
The client entering a new map does not want/need constant full world
state updates. So now we only send 2 full world updates before client
'resumes' and starts receiving incremental ones.
=> Fix a map entering process to solve link/server blocking.

Projects/CoX/Common/GameData/Movement.cpp, Projects/CoX/Common/GameData/NpcStore.cpp, Projects/CoX/Common/GameData/StateInterpolator.cpp, Projects/CoX/Common/GameData/StateStorage.h, Projects/CoX/Common/Messages/Map/ContactList.h, Projects/CoX/Common/Messages/Map/DoorAnims.h, Projects/CoX/Common/Messages/Map/InputState.cpp, Projects/CoX/Servers/MapServer/DataHelpers.cpp, Projects/CoX/Servers/MapServer/DataHelpers.h, Projects/CoX/Servers/MapServer/MessageHelpers.cpp
* m_svr_keypress_time uses a type alias FloatDuration now.
* removed a few useless casts.
* updateContactStatusList takes the parameter by `const &` now.
* fix debug message in `usePower` for `powtpl.pAttribMod[i].Duration >
0` case
* removed/fxied a few 'unused argument' warnings.
=> Use float duration for reporting keypress times + a few small fixes.

Projects/CoX/Common/Messages/Auth/AuthEvents.h
Closes #619 .
- Replace `assert(op==3)` with a conditional warning message.
=> auth: Don't assert on bad reconnection attempts

Projects/CoX/Common/GameData/Team.cpp, Projects/CoX/Common/GameData/Team.h, Projects/CoX/Servers/AuthDatabase/AuthDBSyncHandler.cpp, Projects/CoX/Servers/GameServer/EmailService/EmailHandler.cpp, Projects/CoX/Servers/MapServer/MapInstance.cpp, Projects/CoX/Servers/MapServer/SlashCommand.cpp, Projects/CoX/Servers/MapServer/WorldSimulation.cpp
This still has issues, to avoid using MapInstance in Team.cpp there is a condition where removing a sidekick can result in one member of the sidekick duo having a "sidekick" state still. This really wont be resolved until #642 is complete.
- The goal of this PR is to prevent the hard crashes when someone removes a team member, or zones while on a team.
- This isn't pretty, but it's supposed to be temporary.
=> Temporary workaround for #555 team-removal and side-kick removal

.travis.yml, Projects/CoX/Common/GameData/power_definitions.h, Projects/CoX/Common/GameData/seq_definitions.h, Projects/CoX/Utilities/SEGSAdmin/NetworkManager.h
Closes #662.
- Added missing header to SEGSAdmin/NetworkManager.h to correct GCC 6.3.1 build error.
- Corrected moc file generation issue which appears under certain conditions and causes builds to fail.
- Temporarily disabling Travis CI macOS builds until the app bundle issue can be resolved.
=> Ubuntu build fixes and ignore Travis macOS builds

Components/serialization_types.h, Projects/CoX/Common/GameData/CommonNetStructures.h, Projects/CoX/Common/GameData/GameDataStore.cpp, Projects/CoX/Common/GameData/GameDataStore.h, Projects/CoX/Common/Runtime/Prefab.cpp, Projects/CoX/Common/Runtime/Prefab.h, Projects/CoX/Common/Runtime/SceneGraph.cpp, include/version.h
Added: GameData now loads up fx infos
Added:  FxInfos are properly recorded in indexed string table ( client
requires the string index to produce power effects )
Fixed: binConverter output is less verbose for  serialized QByteArray
strings
Fixed: When a new SceneGraph is loaded, PrefabStore entries are properly
mareked as not loaded.
Fixed: SceneNode::name should have had it's name set from non-lowercased
value
=> A bunch of scary bugs came trick-or-treating, sweets were applied.

Projects/CoX/Common/GameData/GameDataStore.cpp, Projects/CoX/Servers/MapServer/DataHelpers.cpp, Projects/CoX/Servers/MapServer/SlashCommand.cpp
From a discussion in discord, train is causing asserts due to checking the level higher than you current, which causes expForLevel to assert. I added an error message to train(), and changed the assert in expforlevel into a min0 max49 so we won't have this problem again.
Also, an assert in emails that shouldn't be needed, and 2 returns that are needed to prevent asserting.
=> Less asserts where error messages will work

Projects/CoX/Common/Runtime/SceneGraph.cpp, Projects/CoX/Servers/MapServer/MapInstance.cpp
Spawn correctly on zone change and stop asserts on Pelegrine Island
Closes #695 
Fixes spawning under map (on some zones)
- Replaces the assert in addChildNode() with a qCritical()
- Fixes spawning under the map on some zones by finding the Spawners and using those. Doesn't seem to work everywhere because :man_shrugging:
=> Spawn correctly on zone change and stop asserts on Pelegrine Island

Components/serialization_common.h, Projects/CoX/Common/GameData/Clue.cpp, Projects/CoX/Common/GameData/scenegraph_serializers.cpp, Projects/CoX/Common/GameData/scenegraph_serializers.h, Projects/CoX/Common/Runtime/SceneGraph.cpp, Projects/CoX/Common/Runtime/SceneGraph.h, Projects/CoX/Servers/MapServer/MapInstance.cpp, Projects/CoX/Servers/MapServer/MapInstance.h, Projects/CoX/Servers/MapServer/MapSceneGraph.cpp, Projects/CoX/Servers/MapServer/MapSceneGraph.h, Projects/CoX/Servers/MapServer/NpcGenerator.cpp, Projects/CoX/Servers/MapServer/ScriptingEngine.cpp, Projects/CoX/Servers/MapServer/SlashCommand.cpp
Correct an issue with typecase when loading bin files, and load all spawners into a MultiHash that we can reference for spawning.
Closes #469 
Resolves falling under the map
- Ignore typecase when loading bin files
- Load all spawners on a map into a MultiHash
- Use MultiHash to spawn new characters and properly zone transfer
- Couple minor code cleanups
=> Hash all spawners and use them to spawn and mapxfer

Projects/CoX/Data/mysql/segs_game_mysql_create.sql
Updating a MySQL-server from pre-tailor PR to current develop HEAD crashes because of foreign key constraints no longer being taken care of in the correct order.
Having references to old tables which shouldn't exist anymore might feel silly, but it makes the admin life easier.
=> mysql: Unremove `costume` table removal

Projects/CoX/Servers/AuthServer/AdminRPC.cpp, Projects/CoX/Servers/AuthServer/AdminRPC.h
Added additional RPC endpoints, as well as code to read RPC IP and port from settings.cfg
Closes #692 
- Related to issues #692 and #633
- Added code to read the pertinent section from settings.cfg. It looks for AdminRPC and loads IP and port string if it exists. If it does not, it uses a default of 127.0.0.1:6001
- Added RPC endpoint `getStartTime` to return server start time (as UNIX epoch). This enables SEGS WebUI to calculate uptime for the dashboard.
- Added RPC endpoint `ping` to return string "pong" as a check if the server is online. `heyServer` and `helloServer` already exist, but this endpoint and response seem to be a semi-standard method (in that I've seen it in multiple other RPC interfaces).
These RPC services can be seen in action at https://segs.verybadpanda.com (WebUI …
=> Add RPC endpoints and reading from settings file.

.travis.yml, 3rd_party/jcon-cpp/src/CMakeLists.txt, Projects/CoX/Servers/GameDatabase/GameDBSyncContext.cpp
This PR provides a workaround for the failing jcon build under macOS and also re-enables Travis builds for the same platform.
Closes #714
=> Fix jcon build under macOS and re-enable Travis builds

Projects/CoX/Servers/MapServer/ScriptingEngine_Null.cpp
Fixes the missing updateClientContext() errors for those with ENABLE_SCRIPTING_ENGINE set to OFF
- add updateClientContext declaration to ScriptingEngine_NULL.cpp
=> Add updateClientContext declaration

CMakeScripts/Windeployqt.cmake
Updated Windeployqt.cmake to help windeployqt copy the correct version
Closes #702
=> cmake scripts seem to always copy the debug Qt dlls, even for a Release build

README.md
Updated travis badge to new dot com address.
This means it'll go Red now that builds are failing.
=> Updated travis badge to new dot com address [skip ci]

Projects/CoX/Servers/AuthServer/AdminRPC.cpp, Projects/CoX/Servers/AuthServer/AdminRPC.h, Projects/CoX/Servers/AuthServer/main.cpp
Switch the jcon-cpp interface from websockets to TCP.
This is needed for the WebUI to actually work as we don't have any security measures in place and thus preferably only allow local connections to the RPC interface.
Please note that this change breaks the current SEGSAdmin RPC implementation.
- RPC protocol changed from WebSockets to "regular" TCP
- `startWebSocketServer()` renamed to `startRPCServer()`
=> rpc: Switch from websockets to TCP

.gitignore, Components/Logging.cpp, Components/Logging.h, Projects/CoX/Data/settings_template.cfg, Projects/CoX/Servers/AuthServer/AdminRPC.cpp, Projects/CoX/Servers/AuthServer/AdminRPC.h
Update settings_template.cfg with AdminRPC section, with default values and instructions for use. Also added ability for user to specify RPC server type (tcp or websockets) that will be created by AuthServer. 
Does not fully close any issue.
These features are referenced in issues #633, #692, and #742.
- Added:
Config section in settings_template.cfg for AdminRPC settings. 
- Modified:
`Projects/CoX/Servers/AuthServer/AdminRPC.cpp` and `Projects/CoX/Servers/AuthServer/AdminRPC.h` to support selection of RPC server type via config file.
=> Extend AdminRPC server and update settings_template.cfg

Projects/CoX/Servers/AuthServer/AdminRPC.cpp, Projects/CoX/Servers/AuthServer/AdminRPC.h
Removed the versions name from AdminRPC::getVersion and added  
the command AdminRPC::getCodename wich returns the versions name
From a data processing point of view it is better if only one data type  
per field is used in the result output. (str, int, ..)  
inspired by:
```
⌁ root  ~   lsb_release -r
Release:        9.6
⌁ root  ~   lsb_release -c
Codename:       stretch
```
=> AdminRPC: change getVersion output and add getCodename

Projects/CoX/Common/GameData/Character.cpp, Projects/CoX/Common/Messages/Game/GameEvents.cpp, Projects/CoX/Common/Messages/GameDatabase/GameDBSyncEvents.h, Projects/CoX/Servers/GameDatabase/GameDBSyncContext.cpp
- Fix new character not spawning in default map (Outbreak) in certain scenarios
- Add const QString EMPTY_CHAR_NAME = "EMPTY" to replace all uses of "EMPTY" to provide clearer use. Added const in GameDBSyncEvents.h as this file is common across all places "EMPTY" is used.
Closes #753
=> Character creation bug fix and "EMPTY" string tidy

Projects/CoX/Servers/AuthDatabase/AuthDBSyncContext.cpp, Projects/CoX/Servers/GameDatabase/GameDBSyncContext.cpp
There is an option for automatic reconnect for the MySQL database backend.
Seeing as all reported incidents of connection timeouts come from MariaDB users, this quick interim fix feel validated.
Partially #579 - don't close that one just yet.
- Add a connection setting for QMYSQL driver connections.
=> mysql: Interim reconnection fix

Projects/CoX/Servers/AuthServer/main.cpp, Projects/CoX/Utilities/SEGSAdmin/SettingsDialog.cpp
Parsing big endian dates is hard. ( 30th of April `300419` should not be less than 31st of March `310319` )
There is a date format ISO standard for a reason.
Let's use it.
And while we're at it, change the file name format from `[logname]_[date].log` to `[date]_[logname].log` as suggested (and agreed upon) in Discord chat.
=> logging: Name logs with ISO-8601 compliant dates

Projects/CoX/Servers/AuthServer/AdminRPC.cpp, Projects/CoX/Servers/AuthServer/AdminRPC.h
Send all data used for the WebUI statistics table in one command.
This will have to be expanded in the future, but number of online characters, accounts and characters in general is not available at this time afaik.
=> rpc: Add WebUI statistics procedure

3rd_party/jcon-cpp/src/jcon/CMakeLists.txt, 3rd_party/jcon-cpp/src/jcon/json_rpc_endpoint.cpp
Disables asserts which crashes the server when a single bad byte has been received.
Also modify `json_rpc_endpoint.cpp` to be on par with upstream repo.
=> rpc: Build jcon-cpp with -DNDEBUG

CMakeLists.txt, Projects/CoX/Common/GameData/Task.cpp, Projects/CoX/Common/GameData/VisitLocation.cpp, Projects/CoX/Common/GameData/shop_serializers.cpp, Projects/CoX/Servers/AuthServer/main.cpp, Projects/CoX/Servers/MapServer/UnitTests/MapEventRegistry.cpp, include/Version.h
Releases should have their own fixed version number, so we can tell from the logs if someone is using a release package or a dev build. Would be great if there were a way to append build number so we know what build someone is running from github. I can't think of a way to automate that easily.
**Comments on how to handle this moving forward are welcome**
None filed.
- Iterate build number to v0.6.5
=> Updating version for -dev build

Doxyfile
Using `HTML_DYNAMIC_MENUS` in Doxygen 1.8.13 generates HTML that does not render properly within several popular browsers including Firefox and IE. In order to make the generated content appear properly, this option should be disabled.
N/A
- Set `HTML_DYNAMIC_MENUS` to `NO` in Doxyfile
=> Fix funky layout after Doxy generation [skip ci]

Doxyfile, docs/doxy_index.md
Created Doxygen landing page and tuned list of files for inclusion.
Closes Segs/Segs.io#17
- Added Doxygen main page for http://doxy.segs.io/
- Changed image path
- Modified list of file extensions included by parser
=> Add Doxygen main page [skip ci]

Components/serialization_types.h, Projects/CoX/Common/GameData/PlayerProgress.h, Projects/CoX/Common/Messages/Map/VisitMapCells.h, Projects/CoX/Servers/MapServer/DataHelpers.cpp, Projects/CoX/Servers/MapServer/DataHelpers.h, Projects/CoX/Servers/MapServer/MapInstance.cpp
Resolved an issue that, when attempting to access m_visible_map_cells with a map tile index greater than 1024, would throw an array out of bounds error. Problem maps were Talos Island and Peregrine Island.
All instances of type `std::array<bool, 1024>` has been replaced with type `std::vector<bool>` from #818 to allow for resizing of the collection when necessary.
Closes #371 
- Replaced type `std::array<bool, 1024>` with type `std::vector<bool>` in all committed files.
- `VisitMapCells::serializeto` now allocates enough space by using the size of `m_visible_map_cells`.
- `MapInstance::on_minimap_state` resizes the vector to 1024 by default if there is no vector for that specific map. It will also resize the vector if the map tile index is larger than the size of the vector.
- …
=> Resolve issue causing out of bounds error when accessing m_visible_map_cells.

Projects/CoX/Data/pgsql/segs_game_postgres_create.sql, Projects/CoX/Data/pgsql/segs_postgres_create.sql
Fixes the syntax of the PostgreSQL scripts allowing dbtool to use them without error.
Relates to #827
- Fixed `emails` table syntax
- Resolved `(42601) QPSQL: Unable to create query ((null):0, (null))` error
- Added `salt` column to `accounts` table to resolve `SQL_ERROR: QSqlError("42703", "QPSQL: Unable to prepare statement", "ERROR:  column \"salt\" of relation \"accounts\" does not exist\nLINE 1: ...INSERT INTO accounts (username,passw,access_level,salt) VALU...\n` error
- Added `DROP TABLE ...` to head of scripts to mirror MySQL script functionality
- Used standard 4-space indent
- Incremented `supergroups` version field from `1` to `2` in `table_versions` table
- Incremented `accounts` version field from `0` to `1` in `table_versions` table
- Synchronized all `last_update` …
=> Fix PostgreSQL scripts [skip ci]

Projects/CoX/Common/GameData/particlesys_serializers.cpp, Projects/CoX/Common/Messages/Map/VisitMapCells.h, Projects/CoX/Servers/AuthServer/AdminRPC.cpp, Projects/CoX/Servers/MapServer/CritterGenerator.cpp, Projects/CoX/Servers/MapServer/DataHelpers.cpp, Projects/CoX/Servers/MapServer/MapInstance.cpp
Compilation outputs quite a few warnings for minor stuff such as unused variables and/or function arguments.
I decided to comment them out as they don't have any effect currently but could serve a good reminder if someone wants to use something similar in the future.
Look at my changes as deprecation before removal? :sweat_smile:
=> Alleviate some build warnings

Projects/CoX/Utilities/SEGSAdmin/SettingsDialog.cpp
SEGSAdmin generated settings.cfg does not currently pull values from the template file, and makes the assumption that `log_generic` takes a boolean value. This PR corrects this by ignoring `log_generic` for the logging tab (no checkbox will be generated) and by culling the default value from the settings_template.cfg
It also sets a default value for config file version, in case one isn't present.
Closes #846
=> Fix for debug logs not showing with new settings.cfg

Projects/CoX/Common/Messages/Map/VisitMapCells.h
Small tweak to VisitMapCells.h to simplify the math on byte_sum to `byte_sum |= 1<<j;`
=> Simplify byte_sum adjustment in VisitMapCells.h

Projects/CoX/Servers/AuthServer/AuthHandler.cpp, Projects/CoX/Servers/MapServer/MapInstance.cpp
Standardizing `link_is_stale_if_disconnected_for` values
No open issues
- modified `link_is_stale_if_disconnected_for` to 5 sec across all servers
=> Adjust stale link ACE_Time values

Projects/CoX/Common/AuthProtocol/AuthLink.cpp, Projects/CoX/Servers/MapServer/DataHelpers.cpp
This message fires too frequently, because toggle powers are constantly sending stance. It clutters the logs and makes them hard to follow on Red/Blue
We may want to actually change that behavior to only send on activation/deactivation, but for now, let's move this to Animations where it makes more sense and can be toggled.
=> Categorize the "Sending new Powerstance" message [skip ci] 

Projects/CoX/Common/GameData/Entity.cpp, Projects/CoX/Common/GameData/GameDataStore.cpp, Projects/CoX/Common/GameData/GameDataStore.h, Projects/CoX/Data/settings_template.cfg, Projects/CoX/Servers/MapServer/MapInstance.cpp, Projects/CoX/Servers/MapServer/MapInstance.h, Projects/CoX/Utilities/SEGSAdmin/SettingsDialog.cpp, Projects/CoX/Utilities/SEGSAdmin/SettingsDialog.ui
Adds option for ticks per second.
Default is 30. 0 errors, and over 100 acts strange. 
Added ui for setting and saving ticks per second option with reasonable minimum and maximum.
The faster the tick rate, the more updates are pushed per second, pretty straightforward.
Please include a summary of this pull request here.
Closes #791
https://github.com/Segs/Segs/issues/791
=> Adds option for ticks per second

Projects/CoX/Servers/MapServer/MapInstance.cpp
Doesn't help find the targets on other maps, but this should remove some crashes for now
=> Fix bug of tells to unfound targets causing crash

Projects/CoX/Servers/MapServer/SlashCommand.cpp
Refactor slash command arg parsing along with some other related cleanup.
Closes https://github.com/Segs/Segs/issues/741
Related to/partly resolves https://github.com/Segs/Segs/issues/756
- Pass in list of params instead of raw command string
- This causes a few changes to how we count/extract params passed into cmd handlers
- Also allows us to use the same cmd parsing regex for all cmd handlers
- Also no longer passing in the command itself e.g. `/dialog`
- Updated some of the log messages (though many are still not consistent across functions/duplicate info with `cmdlist` - seems like this could be done in a separate PR)
- Removed/replaced old helper functions
- Some misc clean up
- Cleaned up some formatting
- Fixed some type conversion warnings
=> Slash command refactor

Projects/CoX/Common/GameData/GameDataStore.cpp, Projects/CoX/Utilities/SEGSAdmin/SettingsDialog.cpp, include/Version.h
Hotfix for the `world_update_ticks_per_sec == 0` issue
Closes #886 
- Iterate s_config_version to 2
- Added default value of 30 to world_update_ticks_per_sec in two files
=> world_update_ticks_per_sec hotfix

Projects/CoX/Utilities/dbtool/DBConnection_Create.cpp
Fix for failed SQLite Database removal on Windows
- `close()` `close()` `close()`
=> Fix for windows sqlite database removal issues
