Segs/Segs

- Projects/CoX/Common/Servers/CRUD_Link.h
- Projects/CoX/Common/Servers/crud_link.inl
- Projects/CoX/Servers/GameServer/GameHandler.cpp
- Projects/CoX/Servers/GameServer/GameHandler.h
- Projects/CoX/Servers/GameServer/GameServer.cpp
- Projects/CoX/Servers/MapServer/Events/EntitiesResponse.cpp
- Projects/CoX/Servers/MapServer/Events/EntitiesResponse.h
Should reduce packet-spam
Also some whitespace cleanup.
> Monitor all connections and only send Idle packets when needed.

- Projects/CoX/Servers/AuthServer/main.cpp
- include/version.h
Also update version information in version.h
> Use QCommandLineParser in AuthServer main

- Components/EventProcessor.cpp
- Projects/CoX/Common/Servers/GameServerInterface.cpp
- Projects/CoX/Common/Servers/GameServerInterface.h
- Projects/CoX/Servers/AdminServer/AdminEvents.h
- Projects/CoX/Servers/AdminServer/AdminLink.cpp
- Projects/CoX/Servers/AdminServer/AdminLink.h
- Projects/CoX/Servers/AdminServer/AdminServer.cpp
- Projects/CoX/Servers/AdminServer/AdminServer.h
- Projects/CoX/Servers/AdminServer/CMakeLists.txt
- Projects/CoX/Servers/AuthServer/AuthLink.h
- Projects/CoX/Servers/GameServer/GameServer.cpp
- Projects/CoX/Servers/GameServer/GameServer.h
This adds getMaxAccountSlots function to GameServer interface.
The Admin Link is a start of remote management support for the admin server.
> Admin link initial work / max account slots support

- Projects/CoX/Common/NetStructures/Entity.cpp
- Projects/CoX/Common/NetStructures/Entity.h
- Projects/CoX/Servers/GameServer/GameServer.cpp
- Projects/CoX/Servers/MapServer/EntityStorage.cpp
Also, who thought the glm::quat constructor had parameters in (w,x,y,z) order ?
Certainly not I :/
work on #94 and functionality to help out with #93 .
> Fix the entity orientation serialization and calculations.

- Projects/CoX/Servers/MapServer/EntityStorage.cpp
- Projects/CoX/Servers/MapServer/Events/ChatMessage.cpp
- Projects/CoX/Servers/MapServer/Events/ChatMessage.h
- Projects/CoX/Servers/MapServer/MapInstance.cpp
Addresses #66 but does not resolve either.
- Add broadcastMessage
- Reset localMessage to local channel
- TODO: restrict local channel to range
> Added broadcast and modified local chat functions. Corrected orientation of other entities on spawn

- Projects/CoX/Servers/MapServer/MapInstance.cpp
- Projects/CoX/Servers/MapServer/MapInstance.h
This should help with implementing future chat functionality.
> Refactor chat processing into it's own function.

- Projects/CoX/Common/GameData/attrib_definitions.h
- Projects/CoX/Common/NetStructures/Character.cpp
- Projects/CoX/Common/NetStructures/Character.h
- Projects/CoX/Common/NetStructures/Entity.cpp
- Projects/CoX/Common/NetStructures/Entity.h
This should resolve the final part of #107
> Send proper character stats, also store them in Character object.

- Projects/CoX/Servers/MapServer/MapServerData.h
> missing file

- Components/BitStream.cpp
- Components/BitStream.h
- Components/Buffer.cpp
- Components/Buffer.h
- Components/FixedPointValue.h
- Projects/CoX/Common/CRUDP_Protocol/CRUDP_Packet.cpp
- Projects/CoX/Common/CRUDP_Protocol/CRUDP_Packet.h
- Projects/CoX/Common/CRUDP_Protocol/CRUDP_Protocol.cpp
- Projects/CoX/Common/NetStructures/Entity.cpp
- Projects/CoX/Common/NetStructures/Entity.h
- Projects/CoX/Servers/AuthServer/main.cpp
- Projects/CoX/Servers/GameServer/GameHandler.cpp
- Projects/CoX/Servers/MapServer/EntityStorage.cpp
- Projects/CoX/Servers/MapServer/EntityStorage.h
- Projects/CoX/Servers/MapServer/EntityUpdateCodec.cpp
- Projects/CoX/Servers/MapServer/Events/EntitiesResponse.cpp
- Projects/CoX/Servers/MapServer/Events/EntitiesResponse.h
- Projects/CoX/Servers/MapServer/Events/InputState.cpp
- Projects/CoX/Servers/MapServer/MapEventFactory.cpp
- Projects/CoX/Servers/MapServer/MapEvents.h
- Projects/CoX/Servers/MapServer/MapInstance.cpp
- Projects/CoX/Servers/MapServer/MapInstance.h
- Projects/CoX/Servers/MapServer/NetCommandManager.h
- Projects/CoX/Servers/MapServer/WorldSimulation.cpp
- Projects/CoX/Utilities/BinConverter/binConverter.cpp
Fixed a bug in networking layer
Fixed non-incremental/incremental entity response packet logic.
Fix some logging functionality
Guard entity array access with a mutex.
various cleanups
> Big one this time

- Projects/CoX/Servers/MapServer/CMakeLists.txt
- Projects/CoX/Servers/MapServer/Events/LocationVisited.cpp
- Projects/CoX/Servers/MapServer/Events/LocationVisited.h
- Projects/CoX/Servers/MapServer/Events/PlaqueVisited.cpp
- Projects/CoX/Servers/MapServer/Events/PlaqueVisited.h
- Projects/CoX/Servers/MapServer/MapEventFactory.cpp
- Projects/CoX/Servers/MapServer/MapEvents.h
- Projects/CoX/Servers/MapServer/MapInstance.cpp
- Projects/CoX/Servers/MapServer/MapInstance.h
Closes #130 .
As a bonus added also a Plaque visited event.
> Add Location and Plaque visited event handlers.

- Projects/CoX/Utilities/dbtool/main.cpp
Addresses #88 
- Switched custom QTextStream qout function to built in QT Message Handlers
- Added color to specific QT Message output because COLORS! Also readability
- Better template file handling and support for multiple PositionalArgs (import multiple files at a time)
- Some minor cleanup
TODO: Needs more testing to ensure it works in all use cases
- Test overwriting current databases
- Test creation of new databases (none exist)
- Test overwriting only one database
- Corrupt one database and test tools ability to fix file
- Test on Windows based systems
- Probably could still use some code cleanup to follow project standards and common practices
> Dbtool v2 with better output and template import

- Projects/CoX/Servers/MapServer/MapEventFactory.cpp
- Projects/CoX/Servers/MapServer/MapEvents.h
- Projects/CoX/Servers/MapServer/MapInstance.cpp
- Projects/CoX/Servers/MapServer/MapInstance.h
> Add inspiration dock mode packet

- Projects/CoX/Servers/MapServer/MapEventFactory.cpp
- Projects/CoX/Servers/MapServer/MapEvents.h
- Projects/CoX/Servers/MapServer/MapInstance.cpp
- Projects/CoX/Servers/MapServer/MapInstance.h
> Add enter door packet

- Projects/CoX/Servers/MapServer/MapEventFactory.cpp
- Projects/CoX/Servers/MapServer/MapEvents.h
- Projects/CoX/Servers/MapServer/MapInstance.cpp
- Projects/CoX/Servers/MapServer/MapInstance.h
> Add packet 36 - stance change

- Projects/CoX/Servers/MapServer/MapEventFactory.cpp
- Projects/CoX/Servers/MapServer/MapEvents.h
- Projects/CoX/Servers/MapServer/MapInstance.cpp
- Projects/CoX/Servers/MapServer/MapInstance.h
> Command packet 11 - Set destination

- Projects/CoX/Servers/MapServer/MapEventFactory.cpp
- Projects/CoX/Servers/MapServer/MapEvents.h
- Projects/CoX/Servers/MapServer/MapInstance.cpp
- Projects/CoX/Servers/MapServer/MapInstance.h
> Command packet 33 - Abort queued power

- Projects/CoX/Servers/MapServer/MapEventFactory.cpp
- Projects/CoX/Servers/MapServer/MapEvents.h
- Projects/CoX/Servers/MapServer/MapInstance.cpp
- Projects/CoX/Servers/MapServer/MapInstance.h
> Command packet 67 - Description and battlecry.

- Projects/CoX/Servers/MapServer/CMakeLists.txt
- Projects/CoX/Servers/MapServer/Events/ClientSettings.cpp
- Projects/CoX/Servers/MapServer/Events/ClientSettings.h
- Projects/CoX/Servers/MapServer/MapEventFactory.cpp
- Projects/CoX/Servers/MapServer/MapEvents.h
- Projects/CoX/Servers/MapServer/MapInstance.cpp
- Projects/CoX/Servers/MapServer/MapInstance.h
> Command event 65 - Client settings data.

- Projects/CoX/Common/Servers/CMakeLists.txt
> Add direct dependency on ace to CoX/Common/Servers

- Projects/CoX/Servers/MapServer/CMakeLists.txt
- Projects/CoX/Servers/MapServer/Events/ChatMessage.cpp
- Projects/CoX/Servers/MapServer/Events/ChatMessage.h
- Projects/CoX/Servers/MapServer/Events/EntitiesResponse.cpp
- Projects/CoX/Servers/MapServer/Events/GameCommandList.cpp
- Projects/CoX/Servers/MapServer/Events/GameCommandList.h
- Projects/CoX/Servers/MapServer/Events/MapEventTypes.h
- Projects/CoX/Servers/MapServer/Events/StandardDialogCmd.h
- Projects/CoX/Servers/MapServer/MapClient.h
- Projects/CoX/Servers/MapServer/MapEvents.h
- Projects/CoX/Servers/MapServer/MapInstance.cpp
+ support for StandardDialogCmd, to test: "/dlg Some text" from client.
> Support for sending server->client command lists.

- Projects/CoX/Common/NetStructures/Entity.h
- Projects/CoX/Servers/MapServer/CMakeLists.txt
- Projects/CoX/Servers/MapServer/EntityStorage.cpp
- Projects/CoX/Servers/MapServer/Events/FloatingDamage.h
- Projects/CoX/Servers/MapServer/Events/GameCommandList.h
- Projects/CoX/Servers/MapServer/Events/InfoMessageCmd.h
- Projects/CoX/Servers/MapServer/Events/MapEventTypes.h
- Projects/CoX/Servers/MapServer/MapClient.h
- Projects/CoX/Servers/MapServer/MapInstance.cpp
- Projects/CoX/Servers/MapServer/WorldSimulation.cpp
Also allow accessing owner client of the Entity ( if it has one. )
> Add FloatingDamage and InfoMessageCmd commands

- Projects/CoX/Servers/MapServer/ScriptingEngine.cpp
Call using:
```lua
client:simple_dialog("Test dialog")
```
> Add simple dialog functionality to LUA

- 3rd_party/lua_sol2/include/sol.hpp
- Projects/CoX/Data/MapInstances/City_00_01/locations.lua
- Projects/CoX/Data/MapInstances/City_00_01/plaques.lua
- Projects/CoX/Servers/MapServer/Events/ChatMessage.cpp
- Projects/CoX/Servers/MapServer/Events/EntitiesResponse.cpp
- Projects/CoX/Servers/MapServer/MapInstance.cpp
- Projects/CoX/Servers/MapServer/MapInstance.h
- Projects/CoX/Servers/MapServer/ScriptingEngine.cpp
- Projects/CoX/Servers/MapServer/ScriptingEngine.h
- Projects/CoX/Servers/MapServer/ScriptingEngine_Null.cpp
We can now implement some partial functionality of show simple dialogs whenever user interacts with a location/plaque.
Related to #136
> Work on making MapInstances scriptable

- docs/CONTRIBUTING.md
Updated CONTRIBUTING.md because card_file_box is much more legible
> Updated CONTRIBUTING.md because card_file_box is much more legible

- 3rd_party/lua_sol2/include/sol.hpp
- Projects/CoX/Common/NetStructures/Character.cpp
- Projects/CoX/Common/NetStructures/Character.h
- Projects/CoX/Common/NetStructures/Powers.cpp
- Projects/CoX/Common/NetStructures/Powers.h
- Projects/CoX/Servers/MapServer/ScriptingEngine.h
> Fix sol2 problem + some work on sending powers

- Projects/CoX/Common/GameData/origin_definitions.h
- Projects/CoX/Servers/MapServer/DataHelpers.cpp
- Projects/CoX/Servers/MapServer/Events/MapEventTypes.h
- Projects/CoX/Servers/MapServer/MapEventFactory.cpp
- Projects/CoX/Servers/MapServer/MapEvents.h
- Projects/CoX/Servers/MapServer/MapInstance.cpp
- Projects/CoX/Servers/MapServer/MapInstance.h
+ fix ContactBonusLength variable type.
Should help with #159, @broxen, it seems it works here, but just to be sure could You test this please ?
> Fixes the class name retrieval bug

- Projects/CoX/Clients/Client_I0/CMakeLists.txt
- Projects/CoX/Clients/Client_I0/renderer/RendererState.cpp
- Projects/CoX/Clients/Client_I0/renderer/RendererState.h
- Projects/CoX/Clients/Client_I0/renderer/RendererUtils.cpp
- Projects/CoX/Clients/Client_I0/utils/dll_patcher.cpp
- Projects/CoX/Servers/MapServer/Events/MapEventTypes.h
- Projects/CoX/Servers/MapServer/MapEventFactory.cpp
- Projects/CoX/Servers/MapServer/MapEvents.h
- Projects/CoX/Servers/MapServer/MapInstance.cpp
- Projects/CoX/Servers/MapServer/MapInstance.h
> Chat channel mask event.

- README.md
- docs/CONTRIBUTING.md
Added links to chat in all the docs, and added a permanent link to the discord channel
> :memo: Added chat to docs

- Projects/CoX/Utilities/piggtool/main.cpp
> Report failure if loadPigg failes

- Projects/CoX/Servers/MapServer/MapInstance.cpp
- Projects/CoX/Servers/MapServer/MapInstance.h
- Give emotes their own private function so as to avoid cluttering `on_console_command`.
- Add in braces to "Snowflakes" `else if` statement, since it is more than one line.
> Refine emotes

- Projects/CoX/Utilities/MapViewer/src/CoHSceneConverter.cpp
- Projects/CoX/Utilities/MapViewer/src/CoHSceneConverter.h
- Projects/CoX/Utilities/MapViewer/src/CohModelConverter.cpp
- Projects/CoX/Utilities/MapViewer/src/MapViewerApp.cpp
- Projects/CoX/Utilities/MapViewer/src/MapViewerApp.h
- Projects/CoX/Utilities/MapViewer/src/SideWindow.cpp
- Projects/CoX/Utilities/MapViewer/src/SideWindow.h
+ Handle crl-ized scene graph format
* correct PYR conversion to urho3d rotation matrix
* correct StaticModel creation, model caching
> Fix + extend map viewer

- Components/EventProcessor.h
- Projects/CoX/Common/AuthProtocol/AuthLink.cpp
- Projects/CoX/Common/AuthProtocol/AuthLink.h
- Projects/CoX/Common/AuthProtocol/Events/AuthorizationProtocolVersion.h
- Projects/CoX/Common/AuthProtocol/Events/LoginRequest.h
- Projects/CoX/Common/CRUDP_Protocol/CRUD_Link.h
- Projects/CoX/Common/Servers/ServerEndpoint.h
- Projects/CoX/Servers/AdminServer/AdminLink.cpp
- Projects/CoX/Servers/AdminServer/AdminLink.h
- Projects/CoX/Servers/AuthServer/AuthClient.cpp
- Projects/CoX/Servers/AuthServer/AuthHandler.cpp
- Projects/CoX/Servers/AuthServer/AuthHandler.h
- Projects/CoX/Servers/GameServer/GameHandler.cpp
- Projects/CoX/Servers/GameServer/GameHandler.h
- Projects/CoX/Servers/MapServer/MapInstance.cpp
- Projects/CoX/Servers/MapServer/MapInstance.h
- Projects/CoX/Utilities/AuthExerciser/DummyClass.cpp
- Projects/CoX/Utilities/AuthExerciser/DummyClass.h
- Projects/CoX/Utilities/AuthExerciser/main.cpp
A bunch of networking and event handling changes. Expect messiness.
> Sync AuthExerciser

- Projects/CoX/Utilities/dbtool/README.md
Closes #233.
- Add a README for SEGS `dbtool` going over its prerequisites and operating instructions.
> Add README for dbtool

- README.md
Need @nemerle to confirm the urls against his Travis/Appveyor accounts
Closes #249
> Added badges for Appveyor, Travis, and statuses

- Components/Settings.cpp
- Projects/CoX/Data/settings.cfg
Fix for some lingering issues from PR #265 
- changed auto generated cfg file to use location_addr for AuthServer
- modified comments to reflect new location_addr use in AuthServer
> Make sure to update your settings.cfg files!

- Projects/CoX/Servers/MapServer/MapEvents.h
Commenting these lines so that the server won't crash under DEBUG when loading in.
> Assert removal

- Projects/CoX/Common/NetStructures/Entity.cpp
- Projects/CoX/Servers/GameServer/GameHandler.cpp
Closes #291 
Small one here.
- Set Access Level for new chars to `1`
- Cleaned up some debug output in GameHandler
> Set Access Level for new chars to 1, cleaned up some debug output

- Projects/CoX/Common/GameData/CMakeLists.txt
- Projects/CoX/Common/GameData/DataStorage.h
- Projects/CoX/Common/GameData/power_definitions.h
- Projects/CoX/Common/GameData/power_serializers.cpp
- Projects/CoX/Common/GameData/power_serializers.h
- Projects/CoX/Utilities/BinConverter/binConverter.cpp
At least people working on powers support will have a starting point
> Power definitions serialization

- Projects/CoX/Data/scripts/motd.smlx
- Projects/CoX/Servers/MapServer/SlashCommand.cpp
- Projects/CoX/Servers/MapServer/SlashCommand.h
Issue #278
- Changed the "/help" slash command to "/cmdlist" or "/commandlist" 
- Added information to each slashcommand we currently have. 
- This is now displayed in it's own separate dialog box and the server console. 
- Added in a check for access_level=0 for @broxen
> Issue278 enh

- Projects/CoX/Servers/AuthServer/AuthHandler.cpp
- Projects/CoX/Servers/AuthServer/AuthServer.cpp
- Projects/CoX/Servers/GameServer/GameHandler.cpp
+ One comment and removal of unused line of code.
> Fix shutdown message type in AuthServer

- .travis.yml
The travis builds are failing while the code compiles fine on clang., Problem is likely with travis environments and fighting with that is no fun.
> Remove clang as a build target on travis.

- Projects/CoX/Servers/AuthDatabase/AuthDBSyncContext.cpp
- Projects/CoX/Servers/AuthServer/AuthHandler.cpp
- Projects/CoX/Servers/AuthServer/AuthHandler.h
- Projects/CoX/Servers/GameDatabase/GameDBSyncContext.cpp
Also handle db errors in auth server
Closes #334 .
> Do not return a DB error on missing accounts

- Projects/CoX/Servers/MapServer/CMakeLists.txt
- Projects/CoX/Servers/MapServer/DataHelpers.cpp
- Projects/CoX/Servers/MapServer/MapInstance.h
- Projects/CoX/Servers/MapServer/SceneGraph.cpp
- Projects/CoX/Servers/MapServer/SceneGraph.h
- Projects/CoX/Servers/MapServer/ScriptingEngine.cpp
- Projects/CoX/Servers/MapServer/SlashCommand.cpp
- Projects/CoX/Servers/MapServer/WorldSimulation.h
It does not do much, just lies there and grins skeletally.
Also expose some bones to script engine.
> Add a skeleton of a SceneGraph

- Projects/CoX/Common/GameData/attrib_definitions.h
- Projects/CoX/Common/GameData/attrib_serializers.cpp
No functional changes just much less crud in the header files.
> Squeeze attrib damage and defense definitions

- Projects/CoX/Servers/AuthServer/main.cpp
In the best of worlds, the number of allocations there would be 0
> Reduce number of allocations in segsLogMessageOutput

- Projects/CoX/Servers/MapServer/WorldSimulation.cpp
Closes #241  .
- Added a function to set m_is_flying within Entity to true on jump event
- 
-
> Fly on jump fix

- Components/BitStream.h
- Components/SEGSEvent.h
- Components/SEGSTimer.h
- Projects/CoX/Common/AuthProtocol/AuthLink.cpp
- Projects/CoX/Common/NetStructures/Entity.h
- Projects/CoX/Servers/AuthServer/AuthHandler.cpp
- Projects/CoX/Servers/AuthServer/AuthHandler.h
- Projects/CoX/Servers/AuthServer/AuthServer.cpp
- Projects/CoX/Servers/AuthServer/AuthServer.h
- Projects/CoX/Servers/AuthServer/main.cpp
- Projects/CoX/Servers/GameServer/GameEventFactory.cpp
- Projects/CoX/Servers/GameServer/GameEventFactory.h
- Projects/CoX/Servers/GameServer/GameEvents.cpp
- Projects/CoX/Servers/GameServer/GameEvents.h
- Projects/CoX/Servers/GameServer/GameHandler.cpp
- Projects/CoX/Servers/GameServer/GameHandler.h
- Projects/CoX/Servers/GameServer/GameLink.cpp
- Projects/CoX/Servers/GameServer/GameLink.h
- Projects/CoX/Servers/GameServer/GameServer.cpp
- Projects/CoX/Servers/GameServer/GameServer.h
- Projects/CoX/Servers/MapServer/Events/GameCommandList.h
- Projects/CoX/Servers/MapServer/Events/InputState.cpp
- Projects/CoX/Servers/MapServer/Events/SidekickOffer.h
> Fix a logic bug when receiving yaw/pitch data from client

- docs/CONTRIBUTING.md
- Added section for binary/ternary operators
- Added Doxygen section
> Update CONTRIBUTING.md [ci skip]

- Projects/CoX/Utilities/dbtool/main.cpp
Old logic created the AccountDatabase inside the CharacterDatabase's db and vice versa.
> Corrected dbtool dbcreation

- Projects/CoX/Servers/AuthServer/main.cpp
- moved `fflush(stderr)` so that we're always flushing the output cache
also :toilet: hehehehe :rofl:
> Remember to flush!

- Projects/CoX/Common/NetStructures/Entity.h
- Projects/CoX/Data/scripts/motd.smlx
- Projects/CoX/Servers/MapServer/WorldSimulation.cpp
While this breaks position updates, it should at least allow people to run around without the constan rubber-banding.
> Server-sync is now disabled by default

- Projects/CoX/Data/scripts/motd.smlx
Closes #387 
- Updated `motd.smlx` with update summary for user-facing info.
> Updated motd.smlx for 0.5.0 release.

- Projects/CoX/Data/mysql/segs_game_mysql_create.sql
Closes #439 
Fixes skin_color type problem as reported by @Otlichno .
> Change chardb.costume.skin_color datatype for MySQL.

- Projects/CoX/Utilities/dbtool/main.cpp
Closes #432  .
I've started thinking, maybe this could take on a more general approach?
A helper function somewhere which takes a `QSqlError const& q` as argument and depending on the error code prints a prettily formatted error?
> Added busy username error text in dbtool.

- Projects/CoX/docs/README.md
> [skip ci] updated README for install directory

- docs/CONTRIBUTING.md
> Update CONTRIBUTING.md [skip ci]

- Projects/CoX/Servers/AuthDatabase/AuthDBSyncContext.cpp
- Projects/CoX/Servers/AuthDatabase/AuthDBSyncContext.h
- Projects/CoX/Servers/AuthDatabase/AuthDBSyncEvents.h
- Projects/CoX/Servers/AuthDatabase/AuthDBSyncHandler.cpp
- Transform inline queries to constants in the anonymous namespace.
- Move getDbVersion() from private class method into anonymous namespace.
> Improve readability of AuthDBSyncContext.cpp

- Projects/CoX/Servers/AuthServer/main.cpp
- README.md
- Utilities/slav/SLAVLogic.cpp
> Update domain names from segs.nemerle.eu to segs.io

- Projects/CoX/Common/NetStructures/Friend.cpp
- Projects/CoX/Common/NetStructures/Friend.h
- Projects/CoX/Servers/MapServer/SlashCommand.cpp
Change removeFriend to take a friend's name and change cmdHandler_Unfriend to pass the friend's name.
Closes #473 .
- 
- 
-
> Able to remove friend when friend is offline.

- .travis.yml
> Try to fix osx travis build

- .travis.yml
Closes #424 
I accidentally merged this into master. Merging with develop branch.
> Osx travis fix

- Projects/CoX/Common/NetStructures/Friend.cpp
- Projects/CoX/Servers/MapServer/MapInstance.cpp
> Friend fix

- appveyor.yml
Closes #487
- Add develop branch to Appveyor
> Add develop branch to Appveyor

- Projects/CoX/Utilities/SEGSAdmin/main.cpp
Closes #511 
- Fixes HDPI Scaling for some displays
> Fixed for SEGSAdmin scaling on HDPI displays

- Projects/CoX/Data/mysql/segs_game_mysql_create.sql
Closes # 533
- Changes the Chardata field in mysql to a mediumblob
> Updating chardata to mediumblob

- Components/Settings.cpp
- Projects/CoX/Common/GameData/GameDataStore.cpp
- Projects/CoX/Common/GameData/GameDataStore.h
- Projects/CoX/Data/settings_template.cfg
- Projects/CoX/Servers/MapServer/MapEvents.h
- Projects/CoX/Servers/MapServer/MapInstance.cpp
Allow afk time to be configured in settings.cfg
> Settings for AFKness

- Projects/CoX/Servers/MapServer/MapInstance.cpp
> whoops, renamed variable

- Projects/CoX/Common/NetStructures/CharacterHelpers.cpp
- Projects/CoX/Common/NetStructures/Powers.cpp
- Projects/CoX/Common/NetStructures/Powers.h
- Projects/CoX/Servers/MapServer/SlashCommand.cpp
FinalizeLevel needs to be called after level changes otherwise inspirations (and other things) might break
> Finalizelevel

- Projects/CoX/Common/NetStructures/Powers.cpp
> Missing Bracket in Powers.cpp

- Projects/CoX/Common/GameData/GameDataStore.cpp
- Projects/CoX/Common/GameData/GameDataStore.h
- Projects/CoX/Common/GameData/power_definitions.h
- Projects/CoX/Common/NetStructures/Entity.h
- Projects/CoX/Servers/MapServer/CMakeLists.txt
- Projects/CoX/Servers/MapServer/DataHelpers.cpp
- Projects/CoX/Servers/MapServer/DataHelpers.h
- Projects/CoX/Servers/MapServer/Events/GameCommandList.h
- Projects/CoX/Servers/MapServer/Events/MapEventTypes.h
- Projects/CoX/Servers/MapServer/Events/Waypoints.h
- Projects/CoX/Servers/MapServer/MapEvents.h
- Projects/CoX/Servers/MapServer/MapInstance.cpp
- Projects/CoX/Servers/MapServer/SlashCommand.cpp
Closes #546 .
**DataHelpers.cpp usePower()**
- PowerType, Range, Accuracy, and TargetType are taken from the power's data, and tested against the target.
- Started to implement damage and healing from powers, but it will need much more work. 
- The batman soundeffects are still there for powers that don't have attribute data.
**GameDataStore.cpp**
- Hardcoded values for some powers, to better test the above.
**power_definitions.h**
- Filled in some values from powers.bin
> Power use improvements

- Projects/CoX/Common/NetStructures/Powers.cpp
- Projects/CoX/Servers/MapServer/DataHelpers.cpp
- Projects/CoX/Servers/MapServer/ScriptingEngine.cpp
- Projects/CoX/Servers/MapServer/SlashCommand.cpp
Since #606 seems to have crashing issues, I thought I'd pull out the important bug fixes and leave the code cleanups for later.
- Fix name.compare check in usePower
- Fix missing m_update_powers in ScriptingEngine.cpp by moving flags into the methods that require them.
> Let's see if we can get these power updates in.

- README.md
> Changed QT download link

- Projects/CoX/Common/GameData/entitydata_definitions.h
- Projects/CoX/Common/NetStructures/Character.cpp
- Projects/CoX/Servers/MapServer/MapInstance.cpp
Super Duper Awesome Mighty Infinite Alternative to Death-By-Zoning.
> Alternative to Death-By-Zoning

- Projects/CoX/Utilities/SEGSAdmin/SEGSAdminTool.ui
- The text was getting cut off
- The 2 bottom-most buttons had the same tooltip
> Adjusted the gui a little

- Projects/CoX/Data/mysql/segs_game_mysql_create.sql
modified:   Projects/CoX/Data/mysql/segs_game_mysql_create.sql
Closes #646 
- Correct SQL commands
- 
-
> Correct typos in MySQL commands

- Projects/CoX/Servers/MapServer/MapServer.cpp
> The map server was not loading runtime support data.

- Projects/CoX/Servers/MapServer/DataHelpers.cpp
- Projects/CoX/Servers/MapServer/MapInstance.cpp
- Projects/CoX/Servers/MapServer/MessageHelpers.cpp
- Projects/CoX/Servers/MapServer/ScriptingEngine.cpp
- Projects/CoX/Servers/MapServer/ScriptingEngine_Null.cpp
Attempt to fix errors in ScriptEngine.cpp and hotfix for setSpeed
Also added really really basic Flight and SS powers
> Attempt to fix errors in ScriptEngine.cpp and hotfix for setSpeed

- Projects/CoX/Data/scripts/motd.smlx
- Projects/CoX/Servers/MapServer/SlashCommand.cpp
- Projects/CoX/docs/README.md
- docs/AUTHORS.md
- include/version.h
Relates to #655 
- Updated Version.h
- Updated motd.smlx
- Updated AUTHORS.md
> [skip ci] update docs, version, and readmes

- Projects/CoX/Common/GameData/Powers.cpp
- Projects/CoX/Common/GameData/Team.cpp
- Projects/CoX/Common/Messages/Map/MapXferRequest.h
- Projects/CoX/Servers/GameServer/EmailService/CMakeLists.txt
- Projects/CoX/Servers/GameServer/FriendshipService/CMakeLists.txt
- Projects/CoX/Servers/MapServer/DataHelpers.cpp
- Projects/CoX/Servers/MapServer/WorldSimulation.cpp
* 2 bugs related to iterating using `for(:)` and erasing entries from
container.
* potential uses of nullptr
* off-by-1 error in Powers.cpp
> A few last-minute fixes 

- Projects/CoX/Common/Runtime/Prefab.cpp
- Projects/CoX/Common/Runtime/SceneGraph.cpp
- Projects/CoX/Common/Runtime/SceneGraph.h
- Projects/CoX/Servers/MapServer/MapSceneGraph.cpp
- Projects/CoX/Utilities/MapViewer/src/CoHSceneConverter.cpp
- Projects/CoX/Utilities/MapViewer/src/CohModelConverter.cpp
- Projects/CoX/Utilities/MapViewer/src/SideWindow.cpp
This should solve the issue of multiple LOD geometries being displayed at the same time.
> Fix LOD problems caused by not applying geometry 'mods'

- Projects/CoX/Common/GameData/GameDataStore.cpp
- Projects/CoX/Common/GameData/GameDataStore.h
- Projects/CoX/Common/GameData/seq_definitions.h
- Projects/CoX/Common/GameData/seq_serializers.cpp
- Projects/CoX/Common/GameData/seq_serializers.h
- Projects/CoX/Utilities/BinConverter/binConverter.cpp
+ timing information for game date load.
> Load sequencer data.

- Projects/CoX/CMakeLists.txt
- Projects/CoX/Common/GameData/CMakeLists.txt
- Projects/CoX/Common/GameData/CharacterData.cpp
- Projects/CoX/Common/GameData/CharacterData.h
- Projects/CoX/Common/GameData/Clue.cpp
- Projects/CoX/Common/GameData/Clue.h
- Projects/CoX/Common/GameData/Entity.cpp
- Projects/CoX/Common/GameData/Entity.h
- Projects/CoX/Common/Messages/Map/CMakeLists.txt
- Projects/CoX/Common/Messages/Map/ClueList.h
- Projects/CoX/Common/Messages/Map/MapEventTypes.h
- Projects/CoX/Data/scripts/City_00_01/entities.lua
- Projects/CoX/Data/scripts/City_00_01/luaBot.lua
- Projects/CoX/Data/scripts/global.lua
- Projects/CoX/Servers/MapServer/DataHelpers.cpp
- Projects/CoX/Servers/MapServer/DataHelpers.h
- Projects/CoX/Servers/MapServer/MapEventFactory.cpp
- Projects/CoX/Servers/MapServer/MapInstance.cpp
- Projects/CoX/Servers/MapServer/MapInstance.h
- Projects/CoX/Servers/MapServer/ScriptingEngine.cpp
Added Clues and Souvenirs to Lua.
Added Random temp power option in Lua.
Updated LuaBot to test new features.
> Clues - Souvenirs - Random Temp powers in Lua

- Projects/CoX/Data/scripts/City_00_01/luaBot.lua
I changed the button types for Train and Titles. Just to see what effect it may have on the client. That borked the luabot script.
This fixes that by adjusting the ID in the luascript.
> Fixed bug I introduced into LuaBot

- Projects/CoX/Data/scripts/City_00_01/luaBot.lua
Hotfix to correct the issue of LuaBot.Mode getting confused when Training or Title window are loaded.
> Hotfix for Training and Title window LuaBot issues

- CMakeLists.txt
> lua: Set scripting engine default enabled

- docs/COMPILE_AND_INSTALL_UBUNTU.md
add multiverse repo cli to fix problems between different ubuntu flavors.  
rewrote some instructions to be more clear about root/sudo usage  
Closes #727
> Readme: Add Multiverse Repo CLI and some better instructions

- 3rd_party/glm/simd/platform.h
- Projects/CoX/Common/GameData/VisitLocation.cpp
Cleaning up code and attempting to fix build errors.
> Code cleanups and attempted build fix

- Projects/CoX/Common/Runtime/Model.cpp
- Projects/CoX/Servers/MapServer/MapInstance.cpp
- Projects/CoX/Servers/MapServer/MessageHelpers.cpp
- Projects/CoX/Servers/MapServer/ScriptingEngine.cpp
- Projects/CoX/Servers/MapServer/SlashCommand.cpp
Use std::make_unique rather than std::unique_ptr(new T) where possible
Closes #532
> Replace `std::unique_ptr<T>(newT())` with `std::make_unique()` calls

- Projects/CoX/Utilities/SEGSAdmin/SEGSAdminTool.cpp
Change use of function from appendPlainText() to insertPlainText()
Closes #761
> Stop excessive blank lines in SEGSAdmin output

- Utilities/event_gen/main.cpp
Fix GCC build issue on Linux
-Add MapServerEvents BitStream include in event_gen/main.cpp
> Fix for GCC / Linux build

- 3rd_party/jcon-cpp/README.md
- 3rd_party/jcon-cpp/src/jcon/json_rpc_client.cpp
- 3rd_party/jcon-cpp/src/jcon/json_rpc_server.cpp
- 3rd_party/jcon-cpp/src/jcon/json_rpc_server.h
- 3rd_party/jcon-cpp/src/jcon/json_rpc_tcp_server.cpp
- 3rd_party/jcon-cpp/src/jcon/json_rpc_tcp_server.h
- 3rd_party/jcon-cpp/src/jcon/json_rpc_websocket_server.cpp
- 3rd_party/jcon-cpp/src/jcon/json_rpc_websocket_server.h
Before we start changing Jcon internals to suit us better, let's update it to the most recent commit.
> Update jcon files to upstream joncol/jcon-cpp@97790509ca

- Projects/CoX/docs/README.md
- docs/COH-CLIENT_INSTALL-WINDOWS.md
Cox-Auth wouldn't work for me, I figured it would be good to include how to work around that in the docs.
> Added instructions for manually adding auth registry key if Cox-Auth doesn't work

- Doxyfile
Updated version number and specified log file in `Doxyfile`.
Closes #814
- Doxygen will now generate warning and error output to a file ('segs_doxy.log') rather than to stderr.
> Update version and add logging [skip ci]

- Projects/CoX/Common/GameData/Movement.cpp
Increased ground and air traction and maximum speeds.
> Adjusted surface params

- Projects/CoX/Servers/GameServer/ZoneTransferService/ZoneTransferService.cpp
This PR will check against Segs `mapinstance_refactor` and will fix the issues found in it.
I would refrain from creating further changes such as incorporating the refactored scripting service until the current thing works at least.
> Fix to issues in current Map Instance refactor

- Components/Logging.cpp
- Components/Settings.cpp
- Components/Settings.h
- Projects/CoX/Servers/AuthServer/AuthServer.cpp
- Projects/CoX/Servers/GameDatabase/GameDBSyncContext.cpp
- Projects/CoX/Utilities/dbtool/main.cpp
Resolves the errors @Otlichno was having when using DB Drivers other than QSQLITE
No issue filed
- Resolves issues with settings.cfg not being created properly
- Uses full file path for SQLite but a short name for other db drivers
> Proposed fix for settings file creation and other db drivers

- Projects/CoX/Utilities/SEGSAdmin/AddNewUserDialog.cpp
- Projects/CoX/Utilities/SEGSAdmin/AddNewUserDialog.ui
Add password confirmation to add user flows in SEGSAdmin
Closes #856
> Add password confirmation to add user flows in SEGSAdmin

- docs/SEGS-COMPILE_AND_INSTALL-WINDOWS.md
Fix broken link to `SEGS-CONFIGURE_WITH_SEGSADMIN.md`
N/A
N/A
> Update SEGS admin doc link

- docs/CONTRIBUTING.md
Add wording to the first contribution area to reflect change in the project's stance on leaked code.
Possibly Closes #876 
- Additions include writing SEGS stance on leaked code and the use of it in SEGS, particularly on the first contribution area.
> [ci skip] Update CONTRIBUTING.MD for code stance.

- Projects/CoX/Data/scripts/City_00_01/entities.lua
- Projects/CoX/Data/scripts/City_01_01/entities.lua
- Projects/CoX/Data/scripts/City_01_02/entities.lua
- Projects/CoX/Data/scripts/City_02_01/entities.lua
- Projects/CoX/Data/scripts/City_02_02/entities.lua
- Projects/CoX/Data/scripts/City_03_01/entities.lua
- Projects/CoX/Data/scripts/City_03_02/entities.lua
- Projects/CoX/Data/scripts/Hazard_01_01/entities.lua
- Projects/CoX/Data/scripts/Hazard_02_01/entities.lua
- Projects/CoX/Data/scripts/Hazard_03_01/entities.lua
- Projects/CoX/Data/scripts/motd.smlx
- Projects/CoX/Data/scripts/spawners.lua
- Projects/CoX/Servers/AuthServer/AdminRPC.cpp
- Projects/CoX/Servers/MapServer/MapInstance.cpp
- docs/AUTHORS.md
- include/Version.h
Final items in the push to get us to v0.7.0 release
Closes #861 
Closes #862 
Closes #863 
- Updated Version strings throughout code base
- Remove spurious debug output
- Remove AFK timer if dialogs or menus have been interacted with
> v0.7.0 Release Candidate 1

- Projects/CoX/Common/GameData/GameDataStore.cpp
- Projects/CoX/Data/scripts/motd.smlx
- docs/SEGS-COMPILE_AND_INSTALL-UBUNTU.md
- docs/SEGS-CONFIGURE_WITH_SEGSADMIN.md
Moved to just /data/powers.json for simplicity
added to readme and motd to make sure people see it
Anywhere else?
> Added powers.json to readme

- CMakeLists.txt
- Projects/CoX/Clients/CMakeLists.txt
Per discussion on Discord: added cmake option to enable/disable building client patch
> added cmake option to enable/disable building client patch

- Projects/CoX/Data/mysql/segs_game_mysql_create.sql
- Projects/CoX/Data/pgsql/segs_game_pgsql_create.sql
- Projects/CoX/Data/sqlite/segs_game_sqlite_create.sql
- Projects/CoX/Utilities/dbtool/DatabaseConfig.cpp
DBTool hotfix for items discovered by @cyanpill today in Discord
- Corrects template file name formation during lookup
- Corrects db and character_table versions in database creation scripts
> [ci skip] Dbtool hotfix
